---
- name: Create Grafana directory
  file:
    path: "{{ grafana_install_dir }}"
    state: directory
    mode: '0755'

- name: Copy Dockerfile template
  template:
    src: Dockerfile.j2
    dest: "{{ grafana_install_dir }}/Dockerfile"
    mode: '0644'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ grafana_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Build and start Grafana container
  shell: |
    cd {{ grafana_install_dir }}
    docker-compose up -d --remove-orphans
  args:
    executable: /bin/bash

- name: Wait for Grafana to be ready
  uri:
    url: "http://localhost:{{ grafana_port }}/api/health"
    method: GET
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  ignore_errors: yes 