---
- name: Create Zabbix directory
  file:
    path: "{{ zabbix_install_dir }}"
    state: directory
    mode: '0755'

- name: Copy docker-compose template
  template:
    src: docker-compose.yml.j2
    dest: "{{ zabbix_install_dir }}/docker-compose.yml"
    mode: '0644'

- name: Start Zabbix containers
  shell: |
    cd {{ zabbix_install_dir }}
    docker-compose pull
    docker-compose up -d --remove-orphans
  args:
    executable: /bin/bash

- name: Wait for Zabbix to be ready
  uri:
    url: "http://localhost:{{ zabbix_web_port }}/api_jsonrpc.php"
    method: POST
    body_format: json
    body: |
      {
        "jsonrpc": "2.0",
        "method": "user.login",
        "params": {
          "user": "Admin",
          "password": "zabbix"
        },
        "id": 1
      }
    status_code: 200
  register: result
  until: result.status == 200
  retries: 30
  delay: 10
  ignore_errors: yes 