FROM grafana/grafana:latest

# Zabbix plugin kurulumu
RUN grafana-cli plugins install alexanderzobnin-zabbix-app

# Opsiyonel: Otomatik plugin yüklemesi için restart gerekli
ENV GF_INSTALL_PLUGINS="alexanderzobnin-zabbix-app"

# Opsiyonel: Plugin'i otomatik etkinleştirmek için
ENV GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS="alexanderzobnin-zabbix-app" 